spring.application.name=task-management-system
spring.output.ansi.enabled=ALWAYS
#psql db configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stms?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=${PSQL_DB_PASSWORD}

#JPA configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

#Configure flyway
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

#Configure liquibase
spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
spring.liquibase.contexts=dev
spring.liquibase.default-schema=public

#email otp configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yeasin.arafat@gigatechltd.com
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

#Global Variables
base_url=http://localhost:8080/
task_url=http://localhost:8080/tasks/


#Configure Logging Format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%c{2.}){cyan} - %msg%n
